### ISSUE TITLE
issue installing logstash 6.4.2

### ISSUE THREAD

**Issue by angelbarrera92** [torian/ansible-role-logstash#6]
Hi

I have a playbook with the following role configuration: 

```yaml
---
- name: My Awesome playbook
  hosts: all
  become: true
  roles:
    - role: geerlingguy.java
    - role: ansible-role-logstash
      logstash_version: 6.4.2
      logstash_plugins:
        - logstash-input-beats
        - logstash-output-amazon_es
```

Trying to install logstash 6.4.2 in a centos 7 aws instance, ansible raise an error with the following description: 

```bash
TASK [ansible-role-logstash : Logstash start at boot time] ************************************************************************************************************************************
fatal: [ec2-XX-XX-XXX-XX.eu-central-1.compute.amazonaws.com]: FAILED! => {"changed": false, "msg": "Could not find the requested service logstash: host"} 
```

This error is raised becouse the logstash installation does not install a service file. In order to do that, elasticsearch provides a way to install the service: 

inside: `/usr/share/logstash/bin` or `{{ logstash_install_dir }}/bin` is located a script named: `system-install`. 

[Elasticsearch indicates](https://www.elastic.co/guide/en/logstash/current/config-setting-files.html): 

> system-install script in /usr/share/logstash/bin to build the appropriate startup script for your system.

But this is not executed :(

So... i can make a PR to solve it. Can i afford it?

Thanks
